# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oly1YuLztkix1gD1h_31iCNj2us5-IWl
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("Social_Media_Sentiment_Analysis_AI_Trends_2026.csv")
df.head()
df.info()
df.describe()
df.isnull().sum()